### ISSUE TITLE
How to add multiple authors ? 

### ISSUE THREAD

**Issue by cderv** [mikey-harper/rmarkdown-cookbook#32]
Is it possible to add multiple authors ? 
How ? for which output format ? 

### Related SO question

+ https://stackoverflow.com/questions/26043807/multiple-authors-and-subtitles-in-rmarkdown-yaml

**Comment by mikey-harper** [comment]
I have added part of this to an answer. Your feedback welcome

https://mikey-harper.github.io/rmarkdown-cookbook/adding-multiple-authors-to-document.html

**Comment by cderv** [comment]
This is short and clear ! looks fine to me. 
I let you close issue when thinks are done ? 
I will then report the closed issue in the dashboard, mentioned the related SO questions. If others of the Top 500 are related to one issue, even closed, I'll continue to link to them. 
Does it look fine to you ?

**Comment by mikey-harper** [comment]
Thanks, I will close the issue.

That sounds great :)
